### ISSUE TITLE
Где можно скачать это расширение в рабочем виде?

### ISSUE THREAD

**Issue by MasterPetrik** [Ryuya-dono/WorldArtAnimeHighlighter#1]
Внутри папок вижу только джава скрипты, css файлы и картинки. 
Я к сожалению не силён во всём этом, подскажите пожалуйста, как установить это расширение.

**Comment by RyuyaLikesSleeping** [comment]
Приветствую.
Добавил запакованный файл расширения WorldArtAnimeHighlighter.crx, его достаточно перетащить в окно браузера.
Проблема в том, что Google уже давно не разрешает ставить расширения в обход их магазина и при перезагрузке браузера оно будет выключено с сообщением "Неподдерживаемое расширение отключено".
Решение этой проблемы описано здесь https://stackoverflow.com/a/38011386/5215277.
